### ISSUE TITLE
using ff2mpv with raspberry 3 b

### ISSUE THREAD

**Issue by enricoT** [woodruffw/ff2mpv#12]
im using archlinux armv7h raspberry pi 3 b, i can run mpv only from terminal To  control mpv i can use keyboard keys, q=quit f=switch full video backspace=pause otherwise without terminal I can not stop mpv, add subtitles or change the audio .... At the moment once ff2mpv run mpv, i can only close with sudo killall mpv. To run mpv i need xterm + mpv, so i can use keyboard q, f, j , v , backspace when the focus is on the terminal window. If is possible to add an option , run in terminal using $term or the name defined in in the json file (xterm? lxterminal? ...).

**Comment by woodruffw** [comment]
> At the moment once ff2mpv run mpv, i can only close with sudo killall mpv.

The `q` keybinding doesn't work? That should quit `mpv`, even without an active terminal connected.

> If is possible to add an option , run in terminal using $term or the name defined in in the json file (xterm? lxterminal? ...).

This should be a relatively simple change to either the Python or Ruby client script: just have it spawn a terminal with a shell session (which then spawns `mpv`) instead of `mpv` directly. You should make that change locally, though: the official client scripts intentionally avoid doing anything other than spawning just `mpv`.

**Comment by woodruffw** [comment]
Closing due to lack of information.
