### ISSUE TITLE
Default shortcut key not is compatible with Firefox < v63

### ISSUE THREAD

**Issue by Sporif** [woodruffw/ff2mpv#14]
The secondary modifier Alt causes installation to fail on Waterfox at least. I don't know about other versions.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values

> secondary modifier (optional). If supplied, this must be either "Shift" or (for Firefox ≥ 63) any one of "Ctrl", "Alt", "Command" and "MacCtrl", which has not been used as the main modifier.

**Comment by woodruffw** [comment]
Thanks for the report. I hadn't noticed installation failures on Firefox < 63, so perhaps it's just Waterfox promoting the incompatible keybinding into a failure. Any insight here @clsr?

**Comment by clsr** [comment]
No idea, although making an install fail because of that instead of just 
ignoring the default keybind seems a rather questionable design 
decision.

Perhaps just change the secondary modifier to Shift. You'll probably 
have to choose a different key (e.g. V for video), since C-S-m seems to 
be used for Responsive Design Mode by Firefox.

**Comment by woodruffw** [comment]
> Perhaps just change the secondary modifier to Shift. You'll probably have to choose a different key (e.g. V for video), since C-S-m seems to be used for Responsive Design Mode by Firefox.

Yeah, this sounds like a good workaround. I'll apply it.

**Comment by woodruffw** [comment]
Released as 3.2, should be visible on AMO soon.

**Comment by Sporif** [comment]
@woodruffw Thanks, can confirmed that fixed the issue.
