### ISSUE TITLE
about  the new no-video menu

### ISSUE THREAD

**Issue by S-Aarab** [woodruffw/ff2mpv#30]
I don't realy know how many people use this new menu, for me I found it very anoing, as it adds an extra step to playing videos.
Can you provide it as an optional feather?
thanks for your awesome work.

**Comment by woodruffw** [comment]
Thank you for the kind words!

Yeah, this is the second time it's been brought up. I merged #28 thinking that it would add a side-by-side context menu, but apparently Firefox "intelligently" puts menu items from the same extension into their own group. I'll look into a fix tonight.

**Comment by woodruffw** [comment]
It looks like there's a WONTFIX from Mozilla for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1294429

Sigh. I might just roll back the no-video change, since it was a single person's request.

cc @hexa29 for notice: you'll still be able to get this kind of functionality with ff2mpv, but you'll need to configure it either on the MPV side or the `youtube-dl` side. The easier way to do it is probably to modify one of the native clients to use a custom "ff2mpv" profile, which you then add special youtube-dl options to.

**Comment by LaserEyess** [comment]
Is it possible to still have it configurable somehow? No video is one thing, but the cookies PR looks really interesting so I would like the ability to pass them either for a whitelisted group of domains or unconditionally.

**Comment by woodruffw** [comment]
> Is it possible to still have it configurable somehow? No video is one thing, but the cookies PR looks really interesting so I would like the ability to pass them either for a whitelisted group of domains or unconditionally.

Yes, there's probably a way to do this with the extension configuration API. That's something I've been putting off, because adding a configuration page means fielding an entire new dimension of "your extension is broken" GitHub issues, when this is an extension I made primarily for my own use. 

If someone feels like picking up the cookies PR again (it's been stale for a while), I'd be happy to discuss what a good configuration approach would be. Until then, I'm probably just going to remove the no-video option because I also find it cumbersome.

**Comment by tpikonen** [comment]
> Sigh. I might just roll back the no-video change, since it was a single person's request.

Please do so. As the original poster, I also find the extra menu very annoying.

**Comment by woodruffw** [comment]
I've reverted #28 and published a new version as 3.6. Feel free to open another issue if there are lingering problems.

Also, I'm happy to take volunteers to work on a settings page :wink:
